### Tools
[tools]
# Repo utilities
# Formatters and linters
# renovate: datasource=github-releases depName=DavidAnson/markdownlint-cli2
markdownlint-cli2 = "0.18.1"
# renovate: datasource=github-releases depName=google/yamlfmt
yamlfmt = "0.20.0"
# renovate: datasource=github-tags depName=adrienverge/yamllint
yamllint = "1.37.1"
# renovate: datasource=npm depName=prettier
prettier = "3.7.4"
# renovate: datasource=github-releases depName=donaldgifford/makefmt
"github:donaldgifford/makefmt" = "latest"
# renovate: datasource=github-releases depName=donaldgifford/forge
"github:donaldgifford/forge" = "latest"
# renovate: datasource=github-releases depName=mvdan/sh
shfmt = "3.13.0"
# renovate: datasource=github-tags depName=koalaman/shellcheck extractVersion=^v(?<version>.+)$
shellcheck = "0.11.0"

# tools
# renovate: datasource=github-releases depName=mikefarah/yq
yq = "4.48.1"
# renovate: datasource=github-releases depName=jqlang/jq
jq = "latest"
# renovate: datasource=github-releases depName=donaldgifford/docz
"github:donaldgifford/docz" = "latest"

# Release tools
# renovate: datasource=github-releases depName=mrtazz/checkmake
checkmake = "0.3.2"
# renovate: datasource=github-releases depName=orhun/git-cliff
git-cliff = "2.13.1"
# renovate: datasource=github-releases depName=anchore/syft
syft = "1.42.3"
# renovate: datasource=github-releases depName=localstack/lstk
"github:localstack/lstk" = "0.9.0"
